AWSTemplateFormatVersion: 2010-09-09
Resources:
  StaticSite:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'static-site.yaml'
      Parameters:
        DomainName: lyftbutton.com
        SubDomain: www
  ApexRedirect:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'domain-redirection.yaml'
      Parameters:
        FromDomain: lyftbutton.com
        ToDomain: www.lyftbutton.com
        SSLCertificateArn: !GetAtt StaticSite.Outputs.SSLCertificateArn
        HostedZoneId: !GetAtt StaticSite.Outputs.HostedZoneId
Outputs:
  NameServers:
    Description: Name servers to set in your domain registrar.
    Value: !GetAtt StaticSite.Outputs.NameServers
